# Generated by Django 5.2.6 on 2026-01-31 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
        ('users', '0010_alter_organisation_id_alter_subscriptionplan_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='badges',
            field=models.ManyToManyField(related_name='users_badges', related_query_name='users_badge', to='gamification.badge', verbose_name='Learner badges'),
        ),
    ]
