# Generated by Django 5.2.6 on 2026-01-31 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_name', models.CharField(help_text='Name the child prefers to be called', max_length=50)),
                ('interests', models.JSONField(blank=True, default=list, help_text="Child's interests for personalized content")),
                ('learning_goals', models.TextField(blank=True, help_text='Specific learning goals for this child')),
                ('daily_practice_goal_minutes', models.PositiveIntegerField(default=15, help_text='Daily practice goal in minutes')),
                ('needs_captions', models.BooleanField(default=False)),
                ('larger_text', models.BooleanField(default=False)),
                ('slower_pace', models.BooleanField(default=False)),
                ('parent_approval_required', models.BooleanField(default=True)),
                ('max_daily_minutes', models.PositiveIntegerField(blank=True, help_text='Maximum daily screen time in minutes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_difficulty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_by_children', to='learning.difficultylevel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parental_child_profile', related_query_name='parental_child_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Child Profile',
                'verbose_name_plural': 'Child Profiles',
            },
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_to_child', models.CharField(choices=[('PARENT', 'Parent'), ('GUARDIAN', 'Guardian'), ('TEACHER', 'Teacher'), ('THERAPIST', 'Therapist')], max_length=50)),
                ('email_notifications', models.BooleanField(default=True)),
                ('progress_reports', models.BooleanField(default=True)),
                ('weekly_summary', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('managed_children', models.ManyToManyField(blank=True, help_text='Children accounts managed by this parent', related_name='parental_managed_by_parents', related_query_name='parental_managed_by_parent', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parental_parent_profile', related_query_name='parental_parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parent Profile',
                'verbose_name_plural': 'Parent Profiles',
            },
        ),
        migrations.CreateModel(
            name='ScreenTimeLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_daily_minutes', models.PositiveIntegerField(help_text='Maximum daily screen time in minutes')),
                ('max_weekly_minutes', models.PositiveIntegerField(blank=True, help_text='Maximum weekly screen time in minutes', null=True)),
                ('allowed_start_time', models.TimeField(blank=True, help_text='Earliest time child can use the app', null=True)),
                ('allowed_end_time', models.TimeField(blank=True, help_text='Latest time child can use the app', null=True)),
                ('blocked_days', models.JSONField(blank=True, default=list, help_text='Days of week when app is blocked (0=Monday, 6=Sunday)')),
                ('parent_override_code', models.CharField(help_text='Code for parents to override time limits', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='screen_time_limits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Screen Time Limit',
                'verbose_name_plural': 'Screen Time Limits',
            },
        ),
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateTimeField(auto_now_add=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_practice_minutes', models.PositiveIntegerField(default=0)),
                ('lessons_completed', models.PositiveIntegerField(default=0)),
                ('signs_learned', models.PositiveIntegerField(default=0)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('accuracy_improvement', models.IntegerField(blank=True, help_text='Percentage improvement in accuracy', null=True)),
                ('notes', models.TextField(blank=True, help_text="Additional notes about child's progress")),
                ('achievements', models.JSONField(blank=True, default=list, help_text='List of achievements earned during this period')),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progress Report',
                'verbose_name_plural': 'Progress Reports',
                'ordering': ['-report_date'],
                'indexes': [models.Index(fields=['child', '-report_date'], name='parental_pr_child_i_0dba75_idx'), models.Index(fields=['parent', '-report_date'], name='parental_pr_parent__b6efba_idx')],
            },
        ),
    ]
