# Generated by Django 5.2.6 on 2026-01-31 16:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REVOKED', 'Revoked'), ('COMPLETED', 'Completed')], default='PENDING', max_length=10)),
                ('progress', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_contents', models.ManyToManyField(related_name='course_contents', related_query_name='course_content', to='learning.coursecontent', verbose_name='Course Contents completed')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.course')),
                ('last_content_accessed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.coursecontent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_course_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Legacy Course Enrollment',
                'verbose_name_plural': 'Legacy Course Enrollments',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('last_access_date', models.DateTimeField(blank=True, null=True)),
                ('certificate_issued', models.BooleanField(default=False)),
                ('certificate_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_lessons', models.ManyToManyField(blank=True, related_name='completed_by', to='learning.lesson', verbose_name='Completed lessons')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='learning.course')),
                ('last_lesson_accessed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_accessed_by', to='learning.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_enrollments', related_query_name='progress_enrollment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'indexes': [models.Index(fields=['user', 'status'], name='progress_en_user_id_1eff5a_idx'), models.Index(fields=['course', 'status'], name='progress_en_course__6af97a_idx')],
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateTimeField(auto_now_add=True)),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duration of practice session in minutes')),
                ('signs_learned', models.PositiveIntegerField(default=0)),
                ('signs_reviewed', models.PositiveIntegerField(default=0)),
                ('accuracy_score', models.IntegerField(blank=True, help_text='Accuracy percentage for this session', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('session_type', models.CharField(choices=[('LESSON', 'Lesson Practice'), ('REVIEW', 'Review Session'), ('FREE', 'Free Practice'), ('QUIZ', 'Quiz Practice')], default='FREE', max_length=20)),
                ('signs_practiced', models.ManyToManyField(blank=True, related_name='practice_sessions', to='learning.sign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_practice_sessions', related_query_name='progress_practice_session', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Practice Session',
                'verbose_name_plural': 'Practice Sessions',
                'ordering': ['-session_date'],
                'indexes': [models.Index(fields=['user', '-session_date'], name='progress_pr_user_id_e60355_idx'), models.Index(fields=['session_type'], name='progress_pr_session_5be330_idx')],
            },
        ),
    ]
