# Generated by Django 4.2.13 on 2024-05-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_badge'),
        ('users', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='badges',
            field=models.ManyToManyField(to='learn.badge', verbose_name='Learner badges'),
        ),
    ]
