# Generated by Django 4.2.13 on 2024-05-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_alter_coarseenrollment_progress'),
        ('users', '0006_user_badges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='badges',
            field=models.ManyToManyField(related_name='badges', related_query_name='badge', to='learn.badge', verbose_name='Learner badges'),
        ),
    ]
