# Generated by Django 5.2.6 on 2026-01-31 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('icon', models.ImageField(help_text='Badge icon image', null=True, storage='conf.storage_backend.PublicMediaStorageLittleSigns()', upload_to='')),
                ('badge_type', models.CharField(choices=[('COURSE_COMPLETION', 'Course Completion'), ('SIGN_MASTER', 'Sign Master'), ('STREAK', 'Learning Streak'), ('PARTICIPATION', 'Participation'), ('SPECIAL', 'Special Achievement')], default='SPECIAL', max_length=20)),
                ('points_required', models.PositiveIntegerField(default=0, help_text='Points required to earn this badge')),
                ('is_active', models.BooleanField(default=True)),
                ('is_secret', models.BooleanField(default=False, help_text='Whether this badge is hidden until earned')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['badge_type'], name='gamificatio_badge_t_452943_idx'), models.Index(fields=['is_active'], name='gamificatio_is_acti_972de6_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('is_displayed', models.BooleanField(default=True, help_text='Whether to display this badge on user profile')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_user_badges', related_query_name='gamification_user_badge', to='gamification.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_user_badges', related_query_name='gamification_user_badge', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Badge',
                'verbose_name_plural': 'User Badges',
                'ordering': ['-earned_at'],
                'indexes': [models.Index(fields=['user', '-earned_at'], name='gamificatio_user_id_44649b_idx')],
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
