# Generated by Django 5.2.6 on 2026-01-31 16:47

import conf.storage_backend
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(help_text='Brief description for course cards', max_length=500)),
                ('age_range_min', models.PositiveIntegerField()),
                ('age_range_max', models.PositiveIntegerField()),
                ('cover_image', models.ImageField(help_text='Course cover image', storage=conf.storage_backend.PublicMediaStorage(), upload_to='')),
                ('preview_video', models.FileField(blank=True, help_text='Preview video for the course', null=True, storage=conf.storage_backend.PublicMediaStorageLittleSigns(), upload_to='')),
                ('estimated_duration_minutes', models.PositiveIntegerField(help_text='Estimated time to complete in minutes')),
                ('max_enrollments', models.PositiveIntegerField(blank=True, help_text='Maximum number of students, null for unlimited', null=True)),
                ('is_free', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['-is_featured', 'display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DifficultyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('age_range_min', models.PositiveIntegerField(help_text='Minimum recommended age')),
                ('age_range_max', models.PositiveIntegerField(help_text='Maximum recommended age')),
                ('level_order', models.PositiveIntegerField(default=0)),
                ('color_code', models.CharField(default='#FF6B6B', help_text='Hex color code for UI', max_length=7)),
                ('icon', models.ImageField(blank=True, help_text='Icon representing difficulty level', null=True, storage=conf.storage_backend.PublicMediaStorage(), upload_to='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Difficulty Level',
                'verbose_name_plural': 'Difficulty Levels',
                'ordering': ['level_order'],
            },
        ),
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('video', models.FileField(null=True, storage=conf.storage_backend.PublicMediaStorageLittleSigns(), upload_to='')),
                ('image', models.ImageField(null=True, storage=conf.storage_backend.PublicMediaStorageLittleSigns(), upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.course')),
            ],
            options={
                'verbose_name': 'Legacy Course Content',
                'verbose_name_plural': 'Legacy Course Contents',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='difficulty_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='learning.difficultylevel'),
        ),
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(help_text='Description of how to perform the sign')),
                ('video_demo', models.FileField(help_text='Video demonstration of the sign', storage=conf.storage_backend.PublicMediaStorageLittleSigns(), upload_to='')),
                ('image_demo', models.ImageField(blank=True, help_text='Static image showing the sign', null=True, storage=conf.storage_backend.PublicMediaStorageLittleSigns(), upload_to='')),
                ('thumbnail', models.ImageField(blank=True, help_text='Thumbnail for quick preview', null=True, storage=conf.storage_backend.PublicMediaStorageLittleSigns(), upload_to='')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags for search and filtering')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('difficulty_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signs', to='learning.difficultylevel')),
            ],
            options={
                'ordering': ['word'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('video_content', models.FileField(blank=True, help_text='Main video content for the lesson', null=True, storage=conf.storage_backend.PublicMediaStorageLittleSigns(), upload_to='')),
                ('image_content', models.ImageField(blank=True, help_text='Main image content for the lesson', null=True, storage=conf.storage_backend.PublicMediaStorageLittleSigns(), upload_to='')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of lesson within the course')),
                ('duration_minutes', models.PositiveIntegerField(default=0, help_text='Estimated duration in minutes')),
                ('is_free', models.BooleanField(default=False, help_text='Whether this lesson is available for free preview')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='learning.course')),
                ('signs', models.ManyToManyField(blank=True, help_text='Signs taught in this lesson', related_name='lessons', to='learning.sign')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'ordering': ['course', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SignCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.ImageField(blank=True, null=True, storage=conf.storage_backend.PublicMediaStorage(), upload_to='')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='learning.signcategory')),
            ],
            options={
                'verbose_name': 'Sign Category',
                'verbose_name_plural': 'Sign Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='sign',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signs', to='learning.signcategory'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['slug'], name='learning_co_slug_b348c5_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['difficulty_level'], name='learning_co_difficu_6d58fe_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_published'], name='learning_co_is_publ_83ea91_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_featured'], name='learning_co_is_feat_4cddc6_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['course', 'order'], name='learning_le_course__30756f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('course', 'order')},
        ),
        migrations.AddIndex(
            model_name='sign',
            index=models.Index(fields=['word'], name='learning_si_word_56612a_idx'),
        ),
        migrations.AddIndex(
            model_name='sign',
            index=models.Index(fields=['category'], name='learning_si_categor_4d58cb_idx'),
        ),
        migrations.AddIndex(
            model_name='sign',
            index=models.Index(fields=['difficulty_level'], name='learning_si_difficu_3dd074_idx'),
        ),
    ]
