# Generated by Django 4.2.13 on 2024-05-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learn", "0002_badge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coarseenrollment",
            name="progress",
            field=models.IntegerField(default=0),
        ),
    ]
