# Generated by Django 5.2.6 on 2026-02-07 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisationmembers',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='organisationmembers',
            name='twitter',
        ),
    ]
