# Generated by Django 5.2.6 on 2026-01-31 16:47

import conf.storage_backend
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_statement', models.TextField(verbose_name='little sign mission statement')),
                ('vision_statement', models.TextField(verbose_name='little sign vision statement')),
            ],
            options={
                'verbose_name': 'AboutUs',
                'verbose_name_plural': 'AboutUs',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('general', 'General'), ('pricing', 'Pricing'), ('technical', 'Technical'), ('parental', 'Parental Controls'), ('learning', 'Learning')], default='general', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['category', 'display_order', 'question'],
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_title', models.CharField(max_length=200)),
                ('welcome_subtitle', models.TextField()),
                ('hero_image', models.ImageField(help_text='Main hero image for home page', storage=conf.storage_backend.PublicMediaStorage(), upload_to='')),
                ('feature1_title', models.CharField(max_length=100)),
                ('feature1_description', models.TextField()),
                ('feature1_icon', models.ImageField(blank=True, null=True, storage=conf.storage_backend.PublicMediaStorage(), upload_to='')),
                ('feature2_title', models.CharField(max_length=100)),
                ('feature2_description', models.TextField()),
                ('feature2_icon', models.ImageField(blank=True, null=True, storage=conf.storage_backend.PublicMediaStorage(), upload_to='')),
                ('feature3_title', models.CharField(max_length=100)),
                ('feature3_description', models.TextField()),
                ('feature3_icon', models.ImageField(blank=True, null=True, storage=conf.storage_backend.PublicMediaStorage(), upload_to='')),
                ('cta_title', models.CharField(max_length=200)),
                ('cta_description', models.TextField()),
                ('cta_button_text', models.CharField(default='Get Started', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Page',
                'verbose_name_plural': 'Home Pages',
            },
        ),
        migrations.CreateModel(
            name='OrganisationMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='Full name')),
                ('avatar', models.ImageField(null=True, storage=conf.storage_backend.PublicMediaStorage(), upload_to='', verbose_name='Profile avatar')),
                ('position', models.CharField(max_length=50, verbose_name='Position in company')),
                ('linked_in', models.URLField(null=True, verbose_name='LinkedIn profile link')),
                ('twitter', models.URLField(null=True, verbose_name='Twitter profile link')),
                ('facebook', models.URLField(null=True, verbose_name='Facebook profile link')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_role', models.CharField(help_text='e.g., Parent, Teacher, Student', max_length=50)),
                ('content', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, '1 stars'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], help_text='Rating from 1 to 5 stars')),
                ('avatar', models.ImageField(blank=True, null=True, storage=conf.storage_backend.PublicMediaStorage(), upload_to='')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-is_featured', 'display_order', 'created_at'],
            },
        ),
    ]
