# Generated by Django

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField('accounts_user', 'account_type', models.CharField(choices=[('parent', 'Parent/Guardian'), ('organization', 'Organization/School')], default='parent', max_length=20)),
        migrations.AddField('accounts_user', 'is_email_verified', models.BooleanField(default=False)),
        migrations.AddField('accounts_user', 'email_verification_token', models.UUIDField(default=uuid.uuid4, editable=False)),
        migrations.AddField('accounts_user', 'email_verification_sent_at', models.DateTimeField(null=True, blank=True)),
        migrations.AddField('accounts_user', 'parent_first_name', models.CharField(max_length=50, null=True, blank=True)),
        migrations.AddField('accounts_user', 'parent_last_name', models.CharField(max_length=50, null=True, blank=True)),
        migrations.AddField('accounts_user', 'parent_email', models.EmailField(null=True, blank=True)),
        migrations.AddField('accounts_user', 'parent_phone', models.CharField(max_length=20, null=True, blank=True)),
        migrations.AddField('accounts_user', 'parent_relationship', models.CharField(choices=[('mother', 'Mother'), ('father', 'Father'), ('guardian', 'Guardian'), ('other', 'Other')], max_length=20, null=True, blank=True)),
        migrations.AddField('accounts_user', 'number_of_children', models.PositiveIntegerField(null=True, blank=True)),
        migrations.AddField('accounts_user', 'children_ages', models.CharField(max_length=100, null=True, blank=True)),
        migrations.AlterField(
            model_name='organisation',
            name='type_of_org',
            field=models.CharField(choices=[('school', 'School'), ('center', 'Learning Center'), ('ngo', 'NGO'), ('healthcare', 'Healthcare'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField('accounts_organisation', 'created_at', models.DateTimeField(auto_now_add=True)),
        migrations.AddField('accounts_organisation', 'updated_at', models.DateTimeField(auto_now=True)),
        migrations.AlterField(
            model_name='organisation',
            name='org_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='org_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
